In [1]:
print("hello world")

hello world

In [ ]:
%pip install numpy
%pip install pandas
%pip install scikit-learn
%pip install matplotlib
%pip install seaborn
%pip install --upgrade pip
%pip install nltk
%pip install xgboost

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: numpy in C:\Users\DELL\AppData\Roaming\Python\Python314\site-packages (2.4.6)
Note: you may need to restart the kernel to use updated packages.
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pandas in C:\Users\DELL\AppData\Roaming\Python\Python314\site-packages (3.0.3)
Requirement already satisfied: numpy>=2.3.3 in C:\Users\DELL\AppData\Roaming\Python\Python314\site-packages (from pandas) (2.4.6)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\DELL\AppData\Roaming\Python\Python314\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\Users\DELL\AppData\Roaming\Python\Python314\site-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in C:\Users\DELL\AppData\Roaming\Python\Python314\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: scikit-learn in C:\Users\DELL\AppData\Roaming\Python\Python314\site-packages (1.9.0)
Requirement already satisfied: numpy>=1.24.1 in C:\Users\DELL\AppData\Roaming\Python\Python314\site-packages (from scikit-learn) (2.4.6)
Requirement already satisfied: scipy>=1.10.0 in C:\Users\DELL\AppData\Roaming\Python\Python314\site-packages (from scikit-learn) (1.17.1)
Requirement already satisfied: joblib>=1.4.0 in C:\Users\DELL\AppData\Roaming\Python\Python314\site-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: narwhals>=2.0.1 in C:\Users\DELL\AppData\Roaming\Python\Python314\site-packages (from scikit-learn) (2.22.1)
Requirement already satisfied: threadpoolctl>=3.5.0 in C:\Users\DELL\AppData\Roaming\Python\Python314\site-packages (from scikit-learn) (3.6.0)
Note: you may need to restart the kernel to use updated packages.
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: matplotlib in C:\Users\DELL\AppData\Roaming\Python\Python314\site-packages (3.11.0)
Requirement already satisfied: contourpy>=1.0.1 in C:\Users\DELL\AppData\Roaming\Python\Python314\site-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in C:\Users\DELL\AppData\Roaming\Python\Python314\site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in C:\Users\DELL\AppData\Roaming\Python\Python314\site-packages (from matplotlib) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in C:\Users\DELL\AppData\Roaming\Python\Python314\site-packages (from matplotlib) (1.5.0)
Requirement already satisfied: numpy>=1.25 in C:\Users\DELL\AppData\Roaming\Python\Python314\site-packages (from matplotlib) (2.4.6)
Requirement already satisfied: packaging>=20.0 in C:\Users\DELL\AppData\Roaming\Python\Python314\site-packages (from matplotlib) (26.2)
Requirement already satisfied: pillow>=9 in C:\Users\DELL\AppData\Roaming\Python\Python314\site-packages (from matplotlib) (12.2.0)
Requirement already satisfied: pyparsing>=3 in C:\Users\DELL\AppData\Roaming\Python\Python314\site-packages (from matplotlib) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in C:\Users\DELL\AppData\Roaming\Python\Python314\site-packages (from matplotlib) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in C:\Users\DELL\AppData\Roaming\Python\Python314\site-packages (from python-dateutil>=2.7->matplotlib) (1.17.0)
Note: you may need to restart the kernel to use updated packages.
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: seaborn in C:\Users\DELL\AppData\Roaming\Python\Python314\site-packages (0.13.2)
Requirement already satisfied: numpy!=1.24.0,>=1.20 in C:\Users\DELL\AppData\Roaming\Python\Python314\site-packages (from seaborn) (2.4.6)
Requirement already satisfied: pandas>=1.2 in C:\Users\DELL\AppData\Roaming\Python\Python314\site-packages (from seaborn) (3.0.3)
Requirement already satisfied: matplotlib!=3.6.1,>=3.4 in C:\Users\DELL\AppData\Roaming\Python\Python314\site-packages (from seaborn) (3.11.0)
Requirement already satisfied: contourpy>=1.0.1 in C:\Users\DELL\AppData\Roaming\Python\Python314\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.3.3)
Requirement already satisfied: cycler>=0.10 in C:\Users\DELL\AppData\Roaming\Python\Python314\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in C:\Users\DELL\AppData\Roaming\Python\Python314\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in C:\Users\DELL\AppData\Roaming\Python\Python314\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.5.0)
Requirement already satisfied: packaging>=20.0 in C:\Users\DELL\AppData\Roaming\Python\Python314\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (26.2)
Requirement already satisfied: pillow>=9 in C:\Users\DELL\AppData\Roaming\Python\Python314\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (12.2.0)
Requirement already satisfied: pyparsing>=3 in C:\Users\DELL\AppData\Roaming\Python\Python314\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in C:\Users\DELL\AppData\Roaming\Python\Python314\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\Users\DELL\AppData\Roaming\Python\Python314\site-packages (from pandas>=1.2->seaborn) (2026.2)
Requirement already satisfied: six>=1.5 in C:\Users\DELL\AppData\Roaming\Python\Python314\site-packages (from python-dateutil>=2.7->matplotlib!=3.6.1,>=3.4->seaborn) (1.17.0)
Note: you may need to restart the kernel to use updated packages.
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pip in C:\Users\DELL\AppData\Roaming\Python\Python314\site-packages (26.1.2)
Note: you may need to restart the kernel to use updated packages.
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: nltk in C:\Users\DELL\AppData\Roaming\Python\Python314\site-packages (3.9.4)
Requirement already satisfied: click in C:\Users\DELL\AppData\Roaming\Python\Python314\site-packages (from nltk) (8.4.1)
Requirement already satisfied: joblib in C:\Users\DELL\AppData\Roaming\Python\Python314\site-packages (from nltk) (1.5.3)
Requirement already satisfied: regex>=2021.8.3 in C:\Users\DELL\AppData\Roaming\Python\Python314\site-packages (from nltk) (2026.5.9)
Requirement already satisfied: tqdm in C:\Users\DELL\AppData\Roaming\Python\Python314\site-packages (from nltk) (4.68.2)
Requirement already satisfied: colorama in C:\Users\DELL\AppData\Roaming\Python\Python314\site-packages (from click->nltk) (0.4.6)
Note: you may need to restart the kernel to use updated packages.

In [3]:
## importing necessary libraries
import numpy as np ##for numerical computations
import pandas as pd ## Data manipulation and analysis
import matplotlib.pyplot as plt ## for data visualization
%matplotlib inline 

#importing wordcloud for text visualization
try:
    from wordcloud import WordCloud
except ImportError:
    import sys, subprocess
    subprocess.check_call([sys.executable, "-m", "pip", "install", "wordcloud"])
    from wordcloud import WordCloud
# importing NLTK for natural language priocessing tasks
import nltk
from nltk.corpus import stopwords #for stopwords data 
 ## downlaoding NLTK data
nltk.download('stopwords') #downloading stopwords data
nltk.download('punkt') #downloading punkt data for tokenization

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\DELL\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\DELL\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!

True

In [4]:
# Read the CSV file
df=pd.read_csv('spam.csv')
#Display the first few rows of the dataset
df.head()

,v1,v2,Unnamed: 2,Unnamed: 3,Unnamed: 4
0,ham,"Go until jurong point, crazy.. Available only ...",NaN,NaN,NaN
1,ham,Ok lar... Joking wif u oni...,NaN,NaN,NaN
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...,NaN,NaN,NaN
3,ham,U dun say so early hor... U c already then say...,NaN,NaN,NaN
4,ham,"Nah I don't think he goes to usf, he lives aro...",NaN,NaN,NaN

In [5]:
df.drop(['Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4'], axis=1, inplace=True)
df.head()

     v1                                                 v2
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [6]:
## rename the columns for better understanding
df.rename(columns={'v1':'target','v2':'text'}, inplace=True)
df.head()

  target                                               text
0    ham  Go until jurong point, crazy.. Available only ...
1    ham                      Ok lar... Joking wif u oni...
2   spam  Free entry in 2 a wkly comp to win FA Cup fina...
3    ham  U dun say so early hor... U c already then say...
4    ham  Nah I don't think he goes to usf, he lives aro...

Data Preprocessing

In [7]:
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()
df['target'] = encoder.fit_transform(df['target'])
df.head()

   target                                               text
0       0  Go until jurong point, crazy.. Available only ...
1       0                      Ok lar... Joking wif u oni...
2       1  Free entry in 2 a wkly comp to win FA Cup fina...
3       0  U dun say so early hor... U c already then say...
4       0  Nah I don't think he goes to usf, he lives aro...

In [8]:
# checking for the duplicate values in the dataset
x=df.duplicated().sum()
print(f"Number of duplicate rows: {x}")
df.shape

Number of duplicate rows: 403

(5572, 2)

In [9]:
# remove the duolicate values from the dataset
df = df.drop_duplicates(keep='first')
len(df)

5169

Feature Engineering

In [10]:
#importing the porter stemmer for stemming the text data
from nltk.stem import PorterStemmer
#import the string library for string manipulation
import string
stemmer = PorterStemmer()

In [11]:
# Lowercase transformation and text preprocessing function
def transform_text( text):
    # Transform the text to lowercase
    text = text.lower()
    
    # Tokenization using NLTK
    text = nltk.word_tokenize(text)
    
    # Removing special characters
    y = []
    for i in text:
        if i.isalnum():
            y.append(i)
            
    # Removing stop words and punctuation
    text = y[:]
    y.clear()
    
    # Loop through the tokens and remove stopwords and punctuation
    for i in text:
        if i not in stopwords.words('english') and i not in string.punctuation:
            y.append(i)
        
    # Stemming using Porter Stemmer
    text = y[:]
    y.clear()
    for i in text:
        y.append(stemmer.stem(i))
    
    # Join the processed tokens back into a single string
    return " ".join(y)

In [12]:
import sys
import nltk
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer
import string
!{sys.executable} -m pip install --upgrade pip
!{sys.executable} -m pip install nltk wordcloud
nltk.download('stopwords')
nltk.download('punkt_tab')
stemmer = PorterStemmer()

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pip in C:\Users\DELL\AppData\Roaming\Python\Python314\site-packages (26.1.2)
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: nltk in C:\Users\DELL\AppData\Roaming\Python\Python314\site-packages (3.9.4)
Requirement already satisfied: wordcloud in C:\Users\DELL\AppData\Roaming\Python\Python314\site-packages (1.9.6)
Requirement already satisfied: click in C:\Users\DELL\AppData\Roaming\Python\Python314\site-packages (from nltk) (8.4.1)
Requirement already satisfied: joblib in C:\Users\DELL\AppData\Roaming\Python\Python314\site-packages (from nltk) (1.5.3)
Requirement already satisfied: regex>=2021.8.3 in C:\Users\DELL\AppData\Roaming\Python\Python314\site-packages (from nltk) (2026.5.9)
Requirement already satisfied: tqdm in C:\Users\DELL\AppData\Roaming\Python\Python314\site-packages (from nltk) (4.68.2)
Requirement already satisfied: numpy>=1.19.3 in C:\Users\DELL\AppData\Roaming\Python\Python314\site-packages (from wordcloud) (2.4.6)
Requirement already satisfied: pillow in C:\Users\DELL\AppData\Roaming\Python\Python314\site-packages (from wordcloud) (12.2.0)
Requirement already satisfied: matplotlib in C:\Users\DELL\AppData\Roaming\Python\Python314\site-packages (from wordcloud) (3.11.0)
Requirement already satisfied: colorama in C:\Users\DELL\AppData\Roaming\Python\Python314\site-packages (from click->nltk) (0.4.6)
Requirement already satisfied: contourpy>=1.0.1 in C:\Users\DELL\AppData\Roaming\Python\Python314\site-packages (from matplotlib->wordcloud) (1.3.3)
Requirement already satisfied: cycler>=0.10 in C:\Users\DELL\AppData\Roaming\Python\Python314\site-packages (from matplotlib->wordcloud) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in C:\Users\DELL\AppData\Roaming\Python\Python314\site-packages (from matplotlib->wordcloud) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in C:\Users\DELL\AppData\Roaming\Python\Python314\site-packages (from matplotlib->wordcloud) (1.5.0)
Requirement already satisfied: packaging>=20.0 in C:\Users\DELL\AppData\Roaming\Python\Python314\site-packages (from matplotlib->wordcloud) (26.2)
Requirement already satisfied: pyparsing>=3 in C:\Users\DELL\AppData\Roaming\Python\Python314\site-packages (from matplotlib->wordcloud) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in C:\Users\DELL\AppData\Roaming\Python\Python314\site-packages (from matplotlib->wordcloud) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in C:\Users\DELL\AppData\Roaming\Python\Python314\site-packages (from python-dateutil>=2.7->matplotlib->wordcloud) (1.17.0)

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\DELL\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\DELL\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!

In [13]:
## transform the text data 
transform_text('Go until jurong point, crazy.. Available only in bugis n great world la e buffet... Cine there got amore wat...')

'go jurong point crazi avail bugi n great world la e buffet cine got amor wat'

In [14]:
df['transformed_text'] = df['text'].apply(transform_text)
df.head()

,target,text,transformed_text
0,0,"Go until jurong point, crazy.. Available only ...",go jurong point crazi avail bugi n great world...
1,0,Ok lar... Joking wif u oni...,ok lar joke wif u oni
2,1,Free entry in 2 a wkly comp to win FA Cup fina...,free entri 2 wkli comp win fa cup final tkt 21...
3,0,U dun say so early hor... U c already then say...,u dun say earli hor u c alreadi say
4,0,"Nah I don't think he goes to usf, he lives aro...",nah think goe usf live around though

In [15]:
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
tfid = TfidfVectorizer(max_features = 500)

In [16]:
X = tfid.fit_transform(df['transformed_text']).toarray()
y = df['target'].values
print(X)
print(y)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[0 0 1 ... 0 0 0]

Train Test Split

In [17]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=2)

Model Training

In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.naive_bayes import MultinomialNB
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.ensemble import BaggingClassifier
from sklearn.ensemble import ExtraTreesClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.naive_bayes import MultinomialNB
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.ensemble import BaggingClassifier
from sklearn.ensemble import ExtraTreesClassifier
from sklearn.ensemble import GradientBoostingClassifier

%pip install xgboost
from xgboost import XGBClassifier

ModuleNotFoundError: No module named 'xgboost'

In [ ]:
svc = SVC(kernel= "sigmoid", gamma  = 1.0)
knc = KNeighborsClassifier()
mnb = MultinomialNB()
dtc = DecisionTreeClassifier(max_depth = 5)
lrc = LogisticRegression(solver = 'liblinear', penalty = 'l1')
rfc = RandomForestClassifier(n_estimators = 50, random_state = 2 )
abc = AdaBoostClassifier(n_estimators = 50, random_state = 2)
bc = BaggingClassifier(n_estimators = 50, random_state = 2)
etc = ExtraTreesClassifier(n_estimators = 50, random_state = 2)
gbdt = GradientBoostingClassifier(n_estimators = 50, random_state = 2)    
xgb  = XGBClassifier(n_estimators = 50, random_state = 2)

In [ ]:
clfs = {
    'SVC': svc,
    'KNN': knc,
    'NB': mnb,
    'DT': dtc,
    'LR': lrc,
    'RF': rfc,
    'Adaboost': abc,
    'Bgc': bc,
    'ETC': etc,
    'GBDT': gbdt,
    'xgb': xgb
    
}

MODEL EVALUATION

In [ ]:
from sklearn.metrics import accuracy_score, confusion_matrix, precision_score, recall_score, f1_score  
def train_classifier(clf, X_train, y_train, X_test, y_test):
    clf.fit(X_train, y_train) ## fit the model
    y_pred = clf.predict(X_test) ## predict the test data
    accuracy = accuracy_score(y_test, y_pred) ## calculate the accuracy score
    precision = precision_score(y_test, y_pred) ## calculate the precision score
    recall = recall_score(y_test, y_pred) ## calculate the recall score
    f1 = f1_score(y_test, y_pred) ## calculate the f1 score
    return accuracy, precision, recall, f1

In [ ]:
accuracy_scores = []
precision_scores = []
recall_scores = []
f1_scores = []
for name, clf in clfs.items():
    current_accuracy, current_precision, current_recall, current_f1 = train_classifier(clf, X_train, y_train, X_test, y_test)
    print(f"for {name} accuracy is {current_accuracy}, precision is {current_precision}, recall is {current_recall}, f1 score is {current_f1}")
    accuracy_scores.append(current_accuracy)
    precision_scores.append(current_precision)
    recall_scores.append(current_recall)
    f1_scores.append(current_f1)